Updated Contributing.md(earlier HACKING) and created CODE_OF_CONDUCT.md
gearman/gearmand pull request #325
Opened 2021-10-05 08:50 UTC by KanishkKhurana

2021-10-05 14:27 UTC, esabol commented
@KanishkKhurana : I'm not sure the first 21 or 22 lines of CONTRIBUTING.md have any long-term usefulness to the project beyond Hacktoberfest. Please delete.

2021-10-05 14:30 UTC, esabol commented
Also, the bulk of the text in CONTRIBUTING.md needs to be converted to Markdown.

2021-10-05 15:38 UTC, KanishkKhurana commented
@esabol 
yes , i'll do this asap

2021-10-05 18:20 UTC, KanishkKhurana commented
@esabol i have added markdown elements to the file. 
please let me know if there are any other changes. 
though i have only been coding for a few months , i get to learn a lot through these simple tasks and thus enjoy it !

2021-10-05 19:53 UTC, esabol commented
Much better, @KanishkKhurana , but I think more Markdown changes need to be made to CONTRIBUTING.md.

If you look at how the file is rendered on GitHub, you see that some lines are word-wrapped that shouldn't be, like the if/then/else block, etc.

Check it out here:

https://github.com/gearman/gearmand/blob/e5784d8d6f29ee3ca92fd5c40f2ff4d220962298/CONTRIBUTING.md

2021-10-05 20:56 UTC, KanishkKhurana commented
@esabol Please review the changes and do let me know if it needs more edits

2021-10-07 16:52 UTC, KanishkKhurana commented
@esabol ,
i have made all the changes you have requested . 
please review them, sorry it took a while .
i request you to please add `hacktoberfest` and `hacktoberfest-accepted` labels to this PR as it will really help me .

2021-10-07 17:14 UTC, esabol requested changes
@KanishkKhurana: Just a few more minor changes and then we are done, I promise!

2021-10-07 17:14 UTC, esabol commented on CONTRIBUTING.md
> +If you are working on the server, here are some handy environmental variables you can set so that you can debug make test:
Please add backticks around "make test".

2021-10-07 17:14 UTC, esabol commented on CONTRIBUTING.md
> +GDB will pause the server while you do run the GDB command.
Please add "Note that " to the beginning of this line and change "do run" to just "run".

2021-10-07 17:14 UTC, esabol commented on CONTRIBUTING.md
> + * GEARMAN_LOG <-- generates a log file for you with the output of the debug for the server
Please add a period at the end of this line.

2021-10-07 17:14 UTC, esabol commented on CONTRIBUTING.md
> +3. Cast return types void when there is a possibility of failure (don't bother with printf, use common sense):  (void)some_function(...);
Please add backticks around "printf" and around "(void)some_function(...);".

2021-10-07 17:14 UTC, esabol commented on CONTRIBUTING.md
> +Happy Hacking :octocat:\
You accidentally deleted the comma before the backslash. Please put it back.

2021-10-12 00:00 UTC, esabol approved these changes

2021-10-16 17:17 UTC, esabol commented
@KanishkKhurana: We were able to resolve our Travis CI issues with this repo. Now, you need to rebase your pull request in order to bring in the changes to the CI setup. Are you familiar with the steps for rebasing a PR? Let me know if you need some guidance on how to do that. Personally, I prefer the method described [here](https://anavarre.net/how-to-rebase-a-github-pull-request/).

2021-10-17 16:00 UTC, esabol commented
> @KanishkKhurana: We were able to resolve our Travis CI issues with this repo. Now, you need to rebase your pull request in order to bring in the changes to the CI setup. Are you familiar with the steps for rebasing a PR? Let me know if you need some guidance on how to do that. Personally, I prefer the method described [here](https://anavarre.net/how-to-rebase-a-github-pull-request/).

Never mind! You don't need to do that. I was thinking of how GitLab CI/CD works. Just restarting the Travis CI jobs that failed before has worked, so I can merge your PR now.

Thanks, @KanishkKhurana !

2021-10-17 16:00 UTC, merged

2021-10-17 16:43 UTC, KanishkKhurana commented
i had started reading the link you had given @esabol but looks like i got lucky . 
thank you !